[book]
authors = ["许杰友 Jieyou Xu (Joe), Buckminsterfullerene"]
language = "en"
multilingual = false
src = "src"
title = "Deep Rock Galactic Modding Handbook"

[rust]
edition = "2021"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/DRG-Modding/docs"
edit-url-template = "https://github.com/DRG-Modding/docs/{path}"
additional-css = ["css/custom.css"]