[book]
authors = ["许杰友 Jieyou Xu (Joe)"]
language = "en"
multilingual = false
src = "src"
title = "Deep Rock Galactic Modding Docs"

[rust]
edition = "2021"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/jieyouxu/drg-modding-docs"
edit-url-template = "https://github.comjieyouxu/drg-modding-docs/{path}"
custom-css = ["custom.css"]
